// Generated by https://quicktype.io

export interface MunicipiosResponse {
    IDMunicipio: string;
    IDProvincia: string;
    IDCCAA:      string;
    Municipio:   string;
    Provincia:   string;
    CCAA:        string;
}
